var quiz = [
//	{"question": "Detta är den första frågan", "1": "bla bla 1", "X": "bla bla 2", "2": "bla bla 3", "correct": "1"},
//	{"question": "Fr", "1": "bla bla 1", "X": "bla bla 2", "2": "bla bla 3", "correct": "1"},
	{"question": "En vit älg som tog ett bad i de värmländska skogarna utanför kommunen Eda blev viral under året 2017. Man räknar med att det finns mellan 50 och 100 vita älgar i Sverige och de flesta befinner sig i Värmland. Varför är älgen vit?", "1": "Albinism, dvs. total avsaknad av färpigmenten melaniner.", "X": "En genetisk mutation där båda föräldrarna måste vara vita för att älgkalven ska bli vit.", "2": "En genetisk mutation där båda föräldrarna inte måste vara vita för att älgkalven ska bli vit.", "correct": "2", "image": "https://www.visitvarmland.se/sites/default/files/styles/bildspel_large/public/blogposts/tedeholm_m_varmland.jpg?itok=kX7r-r3d"},
//	{"question": "Cai Lun, uppfinnaren av den moderna pappersframställningen föddes år 50 (e.Kr.). Vilken bild föreställer honom?", "1": "https://www.paperdiscoverycenter.org/wp-content/uploads/2013/07/lun.jpg", "X": "http://www.nndb.com/people/933/000092657/ivan-the-terrible-2-sized.jpg", "2": "https://images-4.svd.se/v2/images/edea642d-63b8-4c15-b49a-f3348dc0f36c?fit=crop&h=417&q=70&upscale=true&w=625&s=6130f8a6df84e5060a05e654110ada844f153b15", "correct": "1"},
	{"question": "Håkäringen, som finns i svenska vatten, hamnade i rampljuset sommaren 2016. Detta efter att forskare konstaterade att håkäringen kan bli 400 år gammal, möjligen till och med upp till 50x10 (=500) år gammal, vilket gör det till det ryggradsdjur med längst livslängd i hela världen. Vid vilken ålder tror forskare att Håkärringen blir könsmogen?", "1": "50", "X": "100", "2": "150", "correct": "2", "image": "https://imgix.kitcdn.se/https%3A%2F%2Fwp.kit.se%2Fapp%2Fuploads%2F2016%2F08%2F1472544065-1ae446705b522a7121b684c1adc1cf25.jpg?fit=crop&h=600&ixlib=php-1.1.0&w=1200&s=463a19635425d0a0202924f2222f44f1"},
	{"question": "Solskyddsfaktor 50 är den högsta solskyddsfaktor som finns på marknaden. Vad står siffrorna på solskyddsfaktorn för?", "1": "Siffran motsvarar andelen skadlig UVB-strålning som släpps igenom, dvs 1/15, 1/30 eller 1/50.", "X": "Den tid det tar innan man bränner sig, dvs 15, 30 eller 50 minuter.", "2": "Siffran motsvarar andelen skadlig UVB-strålning som blockeras, dvs 15%, 30% eller 50%.", "correct": "1", "image": "http://cdn2.cdnme.se/cdn/6-2/1720603/images/2011/solen_135901182_158402345.jpg"},
	{"question": "Tenn är grundämnet med atomnummer 50. För att utvinna tenn bryts tennmalm som kallas kassiterit. Vilken av följande bilder föreställer kassiterit?", "1": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/4447M-cassiterite.jpg/1200px-4447M-cassiterite.jpg", "X": "https://image.jimcdn.com/app/cms/image/transf/none/path/s3c1e3c49782ca421/image/iec98ba4bcefeb389/version/1487664573/image.png", "2": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/NatCopper.jpg/800px-NatCopper.jpg", "correct":"1"},
	{"question": "Vilket land i Europa har en befolkningsmängd som ligger närmast 50 miljoner?", "1": "Ukraina", "X": "Italien", "2": "Spanien", "correct": "2"},
	{"question": "Siffran 50 betecknas L med romerska siffror. När man skickade (L) i MSN Messenger uppstod ett hjärta. Vad uppstod om man skickade (&)?", "1": "En snigel", "X": "En hund", "2": "En katt", "correct":"X"},
	{"question": "På 50-talet var det mycket populärt med utstående kjolar. Vad kallas den typ av underkjol som gör detta möjligt?", "1": "Petticoat", "X": "Pennkjol", "2":"Tulpankjol", "correct": "1", "image":"https://i.pinimg.com/originals/df/4e/04/df4e045b091a0d4819bf6cc6a37fb475.jpg"}
]
